/*
 * Builds the theme stylesheets that the React4J server selects between (plan-274, plan-277):
 *
 *   public/css/theme/react4j-modern.css   compiled from src/theme/react4j-modern.scss (compressed)
 *   public/css/theme/bootstrap.min.css    a verbatim copy of the stock node_modules/bootstrap/dist/css/bootstrap.min.css
 *   public/css/theme/react4j-tabler.css   Tabler (@tabler/core, MIT) compiled from its Sass sources via
 *                                         src/theme/react4j-tabler.scss, custom properties renamed to the bs- namespace
 *
 * Run by npm as the "prebuild" script, so `npm run build` (and therefore the Maven build) always regenerates them.
 * ANY failure here exits non-zero and aborts the build. The output directory is deleted FIRST, so a failed compile can
 * never be masked by a copy generated by an earlier, successful run.
 *
 * The modern pipeline is deliberately untouched by the Tabler pipeline (no postcss, no autoprefixer, no banner).
 *
 * LICENCE GUARDS of the Tabler pipeline (each one fails the build, see assertTablerSourcesOnly / assertTablerOutput):
 *   - only Sass sources of the pinned @tabler/core package (and our own src/theme) may be loaded, never its prebuilt
 *     output folder and never its bundled third party libraries (some of them are not MIT);
 *   - the output must not mention Google Fonts or the third party chart library;
 *   - every custom property in the output must live in the bs- namespace (except an explicit, reasoned allowlist).
 */
// autoprefixer reads the browserslist from package.json; silence the "caniuse-lite is outdated" notice (build noise only).
process.env.BROWSERSLIST_IGNORE_OLD_DATA = "true";

const fs = require("fs");
const path = require("path");
const { fileURLToPath } = require("url");
const sass = require("sass");
const postcss = require("postcss");
const prefixCustomProperties = require("postcss-prefix-custom-properties");
const autoprefixer = require("autoprefixer");

const root = path.resolve(__dirname, "..");
const outputDirectory = path.join(root, "public", "css", "theme");
const nodeModules = path.join(root, "node_modules");
const scssEntry = path.join(root, "src", "theme", "react4j-modern.scss");
const tablerEntry = path.join(root, "src", "theme", "react4j-tabler.scss");
const stockBootstrap = path.join(nodeModules, "bootstrap", "dist", "css", "bootstrap.min.css");

const TABLER_PACKAGE = "@tabler/core";
const TABLER_PREFIX = "bs-";
const TABLER_SASS_ROOT = path.join(nodeModules, "@tabler", "core", "scss");
const TABLER_ALLOWED_SOURCE_ROOTS = [TABLER_SASS_ROOT, path.join(root, "src", "theme")];

/** Substrings that must never appear (case-insensitive) in react4j-tabler.css. */
const TABLER_FORBIDDEN_OUTPUT = ["fonts.googleapis", "fonts.gstatic", "apexcharts", "dist/libs"];

/**
 * Custom properties that may stay outside the bs- namespace, name -> reason. EMPTY by measurement (2026-10-04): Tabler's
 * Sass emits only unprefixed names, and its own build excludes nothing but --bs-* (names that already carry the target
 * namespace, e.g. the dropdown --bs-position). Add an entry only with a reason.
 */
const TABLER_CUSTOM_PROPERTY_ALLOWLIST = {};

function main() {
    fs.rmSync(outputDirectory, { recursive: true, force: true });
    fs.mkdirSync(outputDirectory, { recursive: true });

    // Bootstrap 5.3 still uses @import (deprecated in Dart Sass, removal only in Sass 3.0). quietDeps hides the
    // warnings raised inside node_modules, and the single @import in our own entry file is silenced explicitly.
    const compiled = sass.compile(scssEntry, {
        loadPaths: [nodeModules],
        style: "compressed",
        sourceMap: false,
        quietDeps: true,
        silenceDeprecations: ["import"],
    });
    fs.writeFileSync(path.join(outputDirectory, "react4j-modern.css"), compiled.css, "utf8");

    // The stock file ends in a sourceMappingURL comment pointing at a .map that is not shipped: strip it so that no
    // dangling reference reaches the browser.
    const stock = fs.readFileSync(stockBootstrap, "utf8").replace(/\/\*#\s*sourceMappingURL=[^*]*\*\/\s*$/, "");
    fs.writeFileSync(path.join(outputDirectory, "bootstrap.min.css"), stock, "utf8");

    const tabler = buildTabler();
    fs.writeFileSync(path.join(outputDirectory, "react4j-tabler.css"), tabler, "utf8");

    console.log(
        "theme: wrote " + path.relative(root, outputDirectory) + " (react4j-modern.css, bootstrap.min.css, react4j-tabler.css)"
    );
}

function buildTabler() {
    const tablerPackage = readJson(path.join(nodeModules, "@tabler", "core", "package.json"));
    assertCondition(tablerPackage.license === "MIT", TABLER_PACKAGE + " declares licence '" + tablerPackage.license + "', expected MIT");

    // Tabler's own Sass uses the module system (@use/@forward). quietDeps keeps third party deprecation noise out of the
    // log; a real compile error still throws.
    const compiled = sass.compile(tablerEntry, {
        loadPaths: [nodeModules],
        style: "compressed",
        sourceMap: false,
        quietDeps: true,
    });
    assertTablerSourcesOnly(compiled.loadedUrls);

    // Both plugins are synchronous, so the LazyResult can be read directly.
    const processed = postcss([prefixCustomProperties({ prefix: TABLER_PREFIX, ignore: [/^--bs-/] }), autoprefixer()]).process(
        stripLeadingByteOrderMark(compiled.css),
        { from: undefined }
    );

    // Tabler's content strings hold a few non-ASCII glyphs (dashes, bullets). Sass would otherwise mark the file with a
    // byte order mark, which cannot sit behind our banner, so escape them: the sheet is then pure ASCII and decodes the
    // same whatever charset the server announces.
    const ascii = processed.css.replace(/[^\x00-\x7F]/gu, (glyph) => "\\" + glyph.codePointAt(0).toString(16) + " ");

    const css = tablerBanner(tablerPackage) + ascii + "\n";
    assertTablerOutput(css);
    return css;
}
function stripLeadingByteOrderMark(css) {
    return css.charCodeAt(0) === 0xfeff ? css.slice(1) : css;
}

function readJson(file) {
    return JSON.parse(fs.readFileSync(file, "utf8"));
}

function assertCondition(condition, message) {
    if (!condition) {
        throw new Error(message);
    }
}

function isInside(parent, child) {
    const relative = path.relative(parent, child);
    return relative !== "" && !relative.startsWith("..") && !path.isAbsolute(relative);
}

/** Guard a: every Sass file the compile loaded lies under Tabler's Sass folder or our own src/theme. */
function assertTablerSourcesOnly(loadedUrls) {
    const offenders = loadedUrls
        .map((url) => (url.protocol === "file:" ? fileURLToPath(url) : url.href))
        .filter((file) => !TABLER_ALLOWED_SOURCE_ROOTS.some((allowed) => isInside(allowed, file)));
    assertCondition(
        offenders.length === 0,
        "licence guard: Sass compile loaded sources outside " +
            TABLER_PACKAGE +
            "/scss and src/theme: " +
            offenders.slice(0, 5).join(", ")
    );
}

/** Guards b and c on the final output. */
function assertTablerOutput(css) {
    const lower = css.toLowerCase();
    TABLER_FORBIDDEN_OUTPUT.forEach((forbidden) =>
        assertCondition(!lower.includes(forbidden), "licence guard: react4j-tabler.css contains forbidden text '" + forbidden + "'")
    );

    const offenders = findNonBootstrapCustomProperties(css).filter((name) => !(name in TABLER_CUSTOM_PROPERTY_ALLOWLIST));
    assertCondition(
        offenders.length === 0,
        "namespace guard: react4j-tabler.css uses custom properties outside the bs- namespace (" +
            offenders.length +
            "): " +
            offenders.slice(0, 8).join(", ")
    );
}

/** Custom property names that do not start with --bs-: declarations, var() references, @property names, any other value token. */
function findNonBootstrapCustomProperties(css) {
    const found = new Set();
    const token = /(?<![A-Za-z0-9_-])--[A-Za-z_][A-Za-z0-9_-]*/g;
    const root = postcss.parse(css);
    const collect = (text) => (text.replace(/url\([^)]*\)/g, "").match(token) || []).forEach((name) => found.add(name));
    root.walkDecls((declaration) => {
        collect(declaration.prop.startsWith("--") ? declaration.prop : "");
        collect(declaration.value);
    });
    root.walkAtRules((rule) => collect(rule.params));
    return [...found].filter((name) => !name.startsWith("--bs-")).sort();
}

function tablerBanner(tablerPackage) {
    const bootstrapLicence = fs.readFileSync(path.join(nodeModules, "bootstrap", "LICENSE"), "utf8");
    const bootstrapCopyright = (bootstrapLicence.match(/^Copyright \(c\) .*$/m) || [])[0];
    assertCondition(bootstrapCopyright, "banner: no copyright line found in the Bootstrap LICENSE file");
    return (
        "/*!\n" +
        " * Tabler v" + tablerPackage.version + " (https://tabler.io)\n" +
        " * Copyright (c) 2018-2026 The Tabler Authors\n" +
        // The second line is Tabler's own dist banner attribution (read for attribution only, nothing is copied from dist),
        // written in ASCII because this sheet is pure ASCII: the author's name is spelled with an l-with-stroke upstream.
        " * Copyright 2018-2026 codecalm.net Pawel Kuna\n" +
        " * Licensed under the MIT licence (https://github.com/tabler/tabler/blob/master/LICENSE)\n" +
        " * Contains Sass derived from Bootstrap (MIT licence), " + bootstrapCopyright + "\n" +
        " * Compiled by React4J from the Tabler Sass sources; custom properties renamed to the " + TABLER_PREFIX + " prefix.\n" +
        " */\n"
    );
}

try {
    main();
} catch (error) {
    console.error("theme: build failed - " + (error && error.message ? error.message : error));
    process.exit(1);
}
