/*
 * Builds the two theme stylesheets that the React4J server selects between (plan-274):
 *
 *   public/css/theme/react4j-modern.css   compiled from src/theme/react4j-modern.scss (compressed)
 *   public/css/theme/bootstrap.min.css    a verbatim copy of the stock node_modules/bootstrap/dist/css/bootstrap.min.css
 *
 * Run by npm as the "prebuild" script, so `npm run build` (and therefore the Maven build) always regenerates them.
 * ANY failure here exits non-zero and aborts the build. The output directory is deleted FIRST, so a failed compile can
 * never be masked by a copy generated by an earlier, successful run.
 */
const fs = require("fs");
const path = require("path");
const sass = require("sass");

const root = path.resolve(__dirname, "..");
const outputDirectory = path.join(root, "public", "css", "theme");
const scssEntry = path.join(root, "src", "theme", "react4j-modern.scss");
const stockBootstrap = path.join(root, "node_modules", "bootstrap", "dist", "css", "bootstrap.min.css");

function main() {
    fs.rmSync(outputDirectory, { recursive: true, force: true });
    fs.mkdirSync(outputDirectory, { recursive: true });

    // Bootstrap 5.3 still uses @import (deprecated in Dart Sass, removal only in Sass 3.0). quietDeps hides the
    // warnings raised inside node_modules, and the single @import in our own entry file is silenced explicitly.
    const compiled = sass.compile(scssEntry, {
        loadPaths: [path.join(root, "node_modules")],
        style: "compressed",
        sourceMap: false,
        quietDeps: true,
        silenceDeprecations: ["import"],
    });
    fs.writeFileSync(path.join(outputDirectory, "react4j-modern.css"), compiled.css, "utf8");

    // The stock file ends in a sourceMappingURL comment pointing at a .map that is not shipped: strip it so that no
    // dangling reference reaches the browser.
    const stock = fs.readFileSync(stockBootstrap, "utf8").replace(/\/\*#\s*sourceMappingURL=[^*]*\*\/\s*$/, "");
    fs.writeFileSync(path.join(outputDirectory, "bootstrap.min.css"), stock, "utf8");

    console.log("theme: wrote " + path.relative(root, outputDirectory) + " (react4j-modern.css, bootstrap.min.css)");
}

try {
    main();
} catch (error) {
    console.error("theme: build failed - " + (error && error.message ? error.message : error));
    process.exit(1);
}
