/*******************************************************************************
 * Copyright 2021 Danny Kunz
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package org.omnaest.react4j.service.internal.service.internal.theme;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;
import org.omnaest.react4j.service.internal.service.RgbColor;

import com.fasterxml.jackson.databind.JsonNode;

/**
 * plan-274 S4 AC4.1, level one: every colour function of the Java mirror against the values Bootstrap's own Sass produced for the same inputs
 * (the fixture is generated by {@code regenerate-golden.js}; nothing here is computed or typed by hand). No mocks.
 */
public class BootstrapColorFunctionsTest
{
    private static final double LUMINANCE_TOLERANCE = 1e-9;

    private final JsonNode      golden              = GoldenFixtures.functionGolden();

    @TestFactory
    public List<DynamicTest> testTintShadeShiftAndMixAgainstBootstrapSassForEveryInputColour()
    {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode colorCase : this.golden.get("colors"))
        {
            String input = colorCase.get("input")
                                    .asText();
            tests.add(DynamicTest.dynamicTest("tint, shade, shift, mix of " + input, () ->
            {
                RgbColor color = RgbColor.parseHex(input);
                JsonNode values = colorCase.get("values");
                for (int weight : new int[] {40, 50, 60, 70, 80})
                {
                    GoldenFixtures.assertColor("tint-color(" + input + ", " + weight + "%)", values.get("--tint-" + weight)
                                                                                                   .asText(),
                                               BootstrapColorFunctions.tintColor(color, weight));
                }
                for (int weight : new int[] {15, 20, 25, 40, 60, 80})
                {
                    GoldenFixtures.assertColor("shade-color(" + input + ", " + weight + "%)", values.get("--shade-" + weight)
                                                                                                    .asText(),
                                               BootstrapColorFunctions.shadeColor(color, weight));
                }
                GoldenFixtures.assertColor("shift-color(" + input + ", 20%)", values.get("--shift-20")
                                                                                    .asText(),
                                           BootstrapColorFunctions.shiftColor(color, 20));
                GoldenFixtures.assertColor("shift-color(" + input + ", -80%)", values.get("--shift-minus-80")
                                                                                     .asText(),
                                           BootstrapColorFunctions.shiftColor(color, -80));
                GoldenFixtures.assertColor("mix(white, " + input + ", 7.5%)", values.get("--mix-white-7_5")
                                                                                    .asText(),
                                           BootstrapColorFunctions.mix(RgbColor.WHITE, color, 7.5));
            }));
        }
        return tests;
    }

    @TestFactory
    public List<DynamicTest> testLuminanceContrastRatioAndColorContrastAgainstBootstrapSassForEveryInputColour()
    {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode colorCase : this.golden.get("colors"))
        {
            String input = colorCase.get("input")
                                    .asText();
            tests.add(DynamicTest.dynamicTest("luminance and contrast of " + input, () ->
            {
                RgbColor color = RgbColor.parseHex(input);
                JsonNode values = colorCase.get("values");
                assertEquals(values.get("--luminance")
                                   .asDouble(),
                             BootstrapColorFunctions.luminance(color), LUMINANCE_TOLERANCE, "luminance(" + input + ")");
                assertEquals(values.get("--contrast-ratio-white")
                                   .asDouble(),
                             BootstrapColorFunctions.contrastRatio(color, RgbColor.WHITE), LUMINANCE_TOLERANCE, "contrast-ratio(" + input + ", white)");
                assertEquals(values.get("--contrast-ratio-black")
                                   .asDouble(),
                             BootstrapColorFunctions.contrastRatio(color, RgbColor.BLACK), LUMINANCE_TOLERANCE, "contrast-ratio(" + input + ", black)");
                assertEquals(GoldenFixtures.color(values.get("--color-contrast")
                                                        .asText()),
                             BootstrapColorFunctions.colorContrast(color), "color-contrast(" + input + ")");
                GoldenFixtures.assertTriplet("to-rgb(" + input + ")", values.get("--to-rgb")
                                                                            .asText(),
                                             BootstrapColorFunctions.toRgb(color));
            }));
        }
        return tests;
    }

    @Test
    public void testTheInputColoursCoverTheExtremesAndBothSidesOfTheContrastFlip()
    {
        boolean white = false;
        boolean black = false;
        boolean flippedToBlack = false;
        boolean keptWhite = false;
        for (JsonNode colorCase : this.golden.get("colors"))
        {
            String input = colorCase.get("input")
                                    .asText();
            white |= "#ffffff".equals(input);
            black |= "#000000".equals(input);
            String contrast = colorCase.get("values")
                                       .get("--color-contrast")
                                       .asText();
            flippedToBlack |= "#000".equals(contrast);
            keptWhite |= "#fff".equals(contrast);
        }
        assertTrue(white && black, "the fixture must hold both extremes");
        assertTrue(flippedToBlack && keptWhite, "the fixture must hold colours on both sides of the contrast flip");
    }

    @Test
    public void testTheLuminanceOfEveryGreyAgainstBootstrapSassCoversTheWholeTabulatedList()
    {
        JsonNode greys = this.golden.get("greyLuminance");
        assertEquals(256, greys.size());
        for (int channel = 0; channel < 256; channel++)
        {
            assertEquals(greys.get(channel)
                              .asDouble(),
                         BootstrapColorFunctions.luminance(RgbColor.of(channel, channel, channel)), LUMINANCE_TOLERANCE, "luminance of grey " + channel);
        }
    }

    @Test
    public void testSassRoundingIsHalfAwayFromZeroWithAFuzzyBoundary()
    {
        assertEquals(63, RgbColor.sassRound(63.2));
        assertEquals(64, RgbColor.sassRound(63.5));
        assertEquals(64, RgbColor.sassRound(63.5 - 1e-12));
        assertEquals(63, RgbColor.sassRound(63.4999));
        assertEquals(0, RgbColor.sassRound(0.2));
    }
}
