/*******************************************************************************
 * Copyright 2021 Danny Kunz
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package org.omnaest.react4j.service.internal.service.internal.theme;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;
import org.omnaest.react4j.service.internal.service.ThemeTokens;

import com.fasterxml.jackson.databind.JsonNode;

/**
 * plan-274 S4 AC4.1 / AC4.4, level three: the whole token stylesheet against the FULL react4j-modern theme compiled by Bootstrap's Sass with the same
 * tokens applied as Sass variables (fixture generated by {@code regenerate-golden.js}). For every token set, every declaration Sass compiled
 * differently from the default theme must be emitted by the renderer with the same value, and every declaration the renderer emits must equal what
 * Sass compiled (the compiled value of this case, or else the default theme as shipped on the classpath). No mocks.
 */
public class ThemeTokenCssSheetGoldenTest
{
    private final JsonNode                          golden   = GoldenFixtures.sheetGolden();
    private final Map<String, CssSheet.Declaration> compiled = lastWins(GoldenFixtures.compiledTheme());

    @TestFactory
    public List<DynamicTest> testTheRendererEmitsExactlyWhatBootstrapSassCompilesForEveryTokenSet()
    {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonNode testCase : this.golden.get("cases"))
        {
            tests.add(DynamicTest.dynamicTest(testCase.get("name")
                                                      .asText(),
                                              () -> this.assertCaseMatchesSass(testCase)));
        }
        return tests;
    }

    @Test
    public void testTheFixtureHoldsAtLeastFiveInputColoursIncludingExtremesAndAContrastFlip()
    {
        List<String> primaries = new ArrayList<>();
        for (JsonNode testCase : this.golden.get("cases"))
        {
            JsonNode primary = testCase.get("tokens")
                                       .get("primary");
            if (primary != null && testCase.get("tokens")
                                           .size() == 1)
            {
                primaries.add(primary.asText());
            }
        }
        assertTrue(primaries.size() >= 5, "primary colours in the fixture: " + primaries);
        for (String required : new String[] {"#4f46e5", "#000000", "#ffffff", "#ffe066"})
        {
            assertTrue(primaries.contains(required), required + " missing from " + primaries);
        }
    }

    @Test
    public void testASassCaseThatChangesNothingIsRecordedAsNoDifferenceSoThatTheComparisonIsNotVacuous()
    {
        int primaryDefaultDifferences = -1;
        int tealDifferences = -1;
        for (JsonNode testCase : this.golden.get("cases"))
        {
            if ("primary-default".equals(testCase.get("name")
                                                 .asText()))
            {
                primaryDefaultDifferences = testCase.get("differing")
                                                    .size();
            }
            if ("primary-teal".equals(testCase.get("name")
                                              .asText()))
            {
                tealDifferences = testCase.get("differing")
                                          .size();
            }
        }
        assertEquals(0, primaryDefaultDifferences, "the default accent must not change the compiled theme");
        assertTrue(tealDifferences > 50, "a different accent must change many declarations, got " + tealDifferences);
    }

    private void assertCaseMatchesSass(JsonNode testCase)
    {
        ThemeTokens tokens = GoldenFixtures.tokens(testCase.get("tokens"));
        Map<String, CssSheet.Declaration> emitted = lastWins(CssSheet.parse(ThemeTokenCss.render(tokens)));
        assertFalse(emitted.isEmpty(), "nothing emitted");

        Map<String, JsonNode> differing = new HashMap<>();
        for (JsonNode item : testCase.get("differing"))
        {
            String key = "|" + item.get("selector")
                                   .asText()
                         + "|" + item.get("property")
                                     .asText();
            differing.put(key, item);
        }

        // completeness: everything Sass changed is emitted, with Sass' value
        List<String> problems = new ArrayList<>();
        for (Map.Entry<String, JsonNode> entry : differing.entrySet())
        {
            CssSheet.Declaration actual = emitted.get(entry.getKey());
            JsonNode expected = entry.getValue();
            if (actual == null)
            {
                problems.add("not emitted: " + entry.getKey() + " (Sass: " + expected.get("value")
                                                                                     .asText()
                             + ")");
                continue;
            }
            String difference = CssValues.describeDifference(expected.get("value")
                                                                     .asText(),
                                                             actual.getValue());
            if (difference != null)
            {
                problems.add(entry.getKey() + ": " + difference);
            }
            if (expected.get("important")
                        .asBoolean() != actual.isImportant())
            {
                problems.add(entry.getKey() + ": important flag differs");
            }
        }

        // soundness: everything emitted is what Sass compiled for this case, or unchanged from the shipped default theme
        for (Map.Entry<String, CssSheet.Declaration> entry : emitted.entrySet())
        {
            if (differing.containsKey(entry.getKey()))
            {
                continue;
            }
            CssSheet.Declaration base = this.compiled.get(entry.getKey());
            if (base == null)
            {
                problems.add("emitted but never compiled by Sass: " + entry.getKey() + " = " + entry.getValue()
                                                                                                    .getValue());
                continue;
            }
            String difference = CssValues.describeDifference(base.getValue(), entry.getValue()
                                                                                   .getValue());
            if (difference != null)
            {
                problems.add("emitted value differs from the unchanged compiled one at " + entry.getKey() + ": " + difference);
            }
            if (base.isImportant() != entry.getValue()
                                           .isImportant())
            {
                problems.add(entry.getKey() + ": important flag differs from the compiled one");
            }
        }
        assertTrue(problems.isEmpty(), () -> problems.size() + " problems, first: " + problems.subList(0, Math.min(5, problems.size())));
    }

    static Map<String, CssSheet.Declaration> lastWins(List<CssSheet.Declaration> declarations)
    {
        Map<String, CssSheet.Declaration> map = new HashMap<>();
        for (CssSheet.Declaration declaration : declarations)
        {
            map.put(declaration.key(), declaration);
        }
        return map;
    }
}
