package org.omnaest.react4j.browser.theme;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.omnaest.react4j.MockApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.ActiveProfiles;

import com.microsoft.playwright.Locator;

/**
 * plan-274 S4, AC4.6: with a primary colour of {@value TokenThemeTestConfiguration#PRIMARY} and a base radius of
 * {@value TokenThemeTestConfiguration#RADIUS} configured through the Java API, a real browser must render the showcase's "Open modal" button in that
 * colour, hover it in the colour Bootstrap's Sass derives, and round it with that radius. Freshness first: the SERVED page must carry the token block,
 * so a stale core or core-ui jar fails loudly instead of making the computed-style assertions meaningless (testing P12).
 */
@Tag("browser")
@SpringBootTest(classes = MockApplication.class, webEnvironment = WebEnvironment.RANDOM_PORT)
@ActiveProfiles(TokenThemeTestConfiguration.PROFILE)
public class TokenThemeIT extends ThemeBrowserSupport
{
    /**
     * Bootstrap Sass' own hover background of {@code .btn-primary} for {@code #0f766e}: {@code shade-color(#0f766e, 15%)}, text copied from
     * {@code react4j-core/src/test/resources/theme/golden/theme-sheet-golden.json} (case primary-teal, generated by regenerate-golden.js)
     */
    private static final String SASS_HOVER_BACKGROUND        = "rgb(5%, 39.3333333333%, 36.6666666667%)";

    /**
     * The exact rgb the browser computes from {@link #SASS_HOVER_BACKGROUND}. The channels are 12.75, 100.3 and 93.5 of 255, so the blue channel sits on a
     * rounding boundary and Chromium (through Playwright) was observed to round it differently on two routes: 93 for an inline {@code style.color}
     * assignment, 94 for a stylesheet rule reading a custom property, which is the route a button takes. No mechanism is asserted. The test reads the
     * browser's own parse through the button's route first, so this pinned value cannot silently drift away from what the Sass text means to the browser.
     */
    private static final String SASS_HOVER_BACKGROUND_AS_RGB = "rgb(13, 100, 94)";

    private static final String MODERN_STYLESHEET_PATH       = "/css/theme/react4j-modern.css";

    @Test
    public void testServedPageCarriesTheTokenStyleBlockAfterTheModernLink()
    {
        String servedHtml = this.fetchServedIndexHtml();
        String head = servedHtml.substring(0, servedHtml.indexOf("</head>"));

        int linkIndex = head.indexOf("<link rel=\"stylesheet\" href=\"" + MODERN_STYLESHEET_PATH + "?");
        int styleIndex = head.indexOf("<style>");
        int appStylesheetIndex = head.indexOf("href=\"/css/color.css");
        assertTrue(linkIndex >= 0, "freshness: no modern theme link in the served head, a stale core jar was probably used: " + head);
        assertTrue(styleIndex > linkIndex, "freshness: the served head carries no token style block after the modern link, a stale core jar was probably used: " + head);
        assertTrue(appStylesheetIndex < 0 || styleIndex < appStylesheetIndex, "the token block must precede the application stylesheets: " + head);
        assertTrue(head.contains("--bs-primary:" + TokenThemeTestConfiguration.PRIMARY), head);
        assertTrue(head.contains(".btn-primary{--bs-btn-color:#fff;--bs-btn-bg:" + TokenThemeTestConfiguration.PRIMARY), head);
    }

    @Test
    public void testOpenModalButtonIsRenderedInTheConfiguredPrimaryColourAndRadius()
    {
        Locator openModalButton = this.openShowcaseAndLocateOpenModalButton();

        assertEquals("rgb(15, 118, 110)", computedStyle(openModalButton, "background-color"));
        assertEquals("rgb(15, 118, 110)", computedStyle(openModalButton, "border-top-color"));
        assertEquals("12px", computedStyle(openModalButton, "border-top-left-radius"));
        assertEquals("12px", computedStyle(openModalButton, "border-bottom-right-radius"));
    }

    @Test
    public void testOpenModalButtonHoverBackgroundIsTheShadeBootstrapSassDerives()
    {
        Locator openModalButton = this.openShowcaseAndLocateOpenModalButton();
        assertEquals("rgb(15, 118, 110)", computedStyle(openModalButton, "background-color"), "not hovered yet");

        // the rgb the browser computes from the text Bootstrap's Sass produced, through the same route a button takes (a stylesheet rule reading a custom
        // property), so that the pinned value is not just what our own output happens to give
        Object browserReading = this.page.evaluate("(text) => { const style = document.createElement('style');"
                                                   + " style.textContent = '.r4j-probe{--r4j-probe-color:' + text + ';background-color:var(--r4j-probe-color)}';"
                                                   + " document.head.appendChild(style); const probe = document.createElement('span'); probe.className = 'r4j-probe';"
                                                   + " document.body.appendChild(probe); const computed = getComputedStyle(probe).backgroundColor; probe.remove();"
                                                   + " style.remove(); return computed; }",
                                                   SASS_HOVER_BACKGROUND);
        assertEquals(SASS_HOVER_BACKGROUND_AS_RGB, browserReading, "the pinned expectation must be what the browser makes of the Sass text");

        openModalButton.hover();
        String hovered = this.awaitComputedStyle(openModalButton, "background-color", SASS_HOVER_BACKGROUND_AS_RGB);

        assertEquals(SASS_HOVER_BACKGROUND_AS_RGB, hovered);
    }

    @Test
    public void testTheTokenBlockIsOneStyleElementWhoseRootVariablesTheBrowserAppliesToTheDocument()
    {
        this.openShowcaseAndLocateOpenModalButton();

        Object styleElements = this.page.evaluate("() => Array.from(document.querySelectorAll('style')).filter(s => s.textContent.includes('--bs-primary:')).length");
        assertEquals(1, ((Number) styleElements).intValue(), "exactly one token style element expected");
        assertEquals(TokenThemeTestConfiguration.PRIMARY, this.page.evaluate("() => getComputedStyle(document.documentElement).getPropertyValue('--bs-primary').trim()"));
        assertEquals(TokenThemeTestConfiguration.RADIUS, this.page.evaluate("() => getComputedStyle(document.documentElement).getPropertyValue('--bs-border-radius').trim()"));
    }

    /**
     * Polls until the property has the expected value or three seconds passed (Bootstrap transitions the button's colours), then returns the last
     * reading, so a failure shows what the browser actually computed
     */
    private String awaitComputedStyle(Locator element, String property, String expected)
    {
        String reading = computedStyle(element, property);
        long deadline = System.currentTimeMillis() + 3000;
        while (!expected.equals(reading) && System.currentTimeMillis() < deadline)
        {
            this.page.waitForTimeout(50);
            reading = computedStyle(element, property);
        }
        return reading;
    }
}
